### ISSUE TITLE
Error after terraform plan.

### ISSUE THREAD

**Issue by jjaimealeman** [digitalocean/supabase-on-do#8]
Excellent write-up, I'm hoping to get this running soon 👍

But I am experiencing a big error with `terraform plan`.

I have properly edited the files with vim in both packer and terraform with my details

I have one project called supabase, one droplet called supabase, and one image snapshot called supabase.
![screenshot](https://i.imgur.com/vwxOVMk.png)

I don't know why it says it can't find the droplet_snapshot "supabase" 🤔

Prevously, the image was called `supabase-yyyymmddhhmmss` but after having this error, I renamed it to supabase, hoping to re-run and get past the error.

Yet, it persists.

And then this part where I added my domain name. It says the name already exists - but it has a red border? So maybe it doesn't? I couldn't find it anywhere in settings.

![screenshot](https://i.imgur.com/RABTLsy.png)

So now I'm really perplexed.

---

In the meantime, I shall await your reply and hopefully that's enough time for the DNS to propagate for the Sendgrid changes to my DNS 👍

**Comment by timothymamo** [comment]
Hi @jjaimealeman  thanks for the feedback.

Just to understand what is happening:

- How were the supabase project, droplet and snapshot created? Manually or via Terraform?
- Was this the first time you ran a `terraform plan` on the directory? Or is error occurring after a subsequent `terraform plan` after you ran a `terraform apply`?
- Also when you say you changed the snapshot name, did you do this manually through the UI? Or changed the name in the data block?

With regards to the domain, that is a strange one indeed as I would expect you to have something like this in the domains tab

![Screenshot 2023-02-03 at 10 30 54](https://user-images.githubusercontent.com/65859835/216564225-7bada94b-4bc8-45bd-b2c7-dac7899bd99a.png)

What is the output of `dig -t ns 915websites.com`?

**Comment by jjaimealeman** [comment]
> How were the supabase project, droplet and snapshot created? Manually or via Terraform?

Everything created manually at `cloud.digitalocean.com`.
  
---

> Was this the first time you ran a terraform plan on the directory? Or is error occurring after a subsequent terraform plan after you ran a terraform apply?

I had not gotten to the `apply` command, only `terraform init` and `terraform plan`.

---

> Also when you say you changed the snapshot name, did you do this manually through the UI? Or changed the name in the data block?

Did that manually at `cloud.digitalocean.com/` so, GUI! Am not sure what a data block is. I made the name change here.
![image](https://user-images.githubusercontent.com/1428292/216576939-d67c8fcd-0220-46ee-a52f-cd0ba85f87fe.png)


---

My DNS (google domains) was previous set to use DigitalOcean servers, but I changed them back to default after having the errors. About a year ago, I had pointed the same domain to a DigitalOcean droplet when I was experimenting with a headless CMS. I guess I had just never changed them back. Do you think that caused my conflict?

![image](https://user-images.githubusercontent.com/1428292/216575798-af4a1b74-f1f1-4860-aa18-461edd5d99f5.png)

Here's the `dig` output.
![image](https://user-images.githubusercontent.com/1428292/216575958-487396e8-998a-4646-b484-e99ed60c530c.png)

**Comment by timothymamo** [comment]
Ah ok. So the first error you are getting is within a terraform `data` block. This `data` block is used to get information from your DigitalOcean account. In the `droplet.tf` file the following data block is looking for a snapshot within your DigitalOcean account:

```
data "digitalocean_droplet_snapshot" "supabase" {
  name_regex  = "^supabase-"
  region      = var.region
  most_recent = true
}
```

We can see that the regex is looking for a snapshot that starts with the name `supabase-` and grabs the most recent one. This information is then used in the `resource` block to create the droplet.
Since you changed the name of the snapshot to only `supabase` terraform cannot find any snapshots starting with `snapshot-`, notice the dash (-) at the end of the name. As we might have multiple snapshots we search for the most common part and get a list taking out the most recent one.
I'd suggest you rename the snapshot to what it previously was, or recreate the snapshot by running packer again (you can run packer as many times as you want and delete the old snapshots).

As for the domain. Still unsure as to why you're not being allowed to add the domain on DigitalOcean. Do you have another DO account where you added this domain to it? That's the only reason I can think of of why you wouldn't be allowed to add the domain.
You'll have to change the nameservers on Google Domains (I'm assuming this is your domain registrar) to what they previously where (DO nameservers) according to the documentation [here](https://docs.digitalocean.com/tutorials/dns-registrars/#instructions).

Once you've done the above (changed the snapshot name, added the domain to DO and set the nameservers on Google Domains) you should be good to go with running the `terraform plan` and `terraform apply` commands.

**Comment by jjaimealeman** [comment]
Thanks for replying Tim.

My `droplet.tf` file shows this (as you mentioned).
![image](https://user-images.githubusercontent.com/1428292/216705843-674b8dc3-7b6a-48ee-85ba-d0760b667000.png)

I reran Packer and my snapshot is named `supabase-20230203202853`. So I still don't understand why it failed in the first place - before I had renamed it. If the regex is looking for `^supabase-` and my snapshot was named `supabase-yyyymmddhhmmss` ... it should never have failed to begin with. 🤔 

---

> As for the domain

This is the only domain I have hosted with DO in the past year of experimentation.

Prior to the error, I had these names set as per the docs from last time.
```
    ns1.digitalocean.com
    ns2.digitalocean.com
    ns3.digitalocean.com
```
So I removed them to start over, but just added them back this morning.

Perhaps I'll wait a 48+ hours for the propagation to take full effect. `dig -t ns ...` currently does show `ns1,2,3 ... DO`.

I will give this another shot come Monday morning, hopefully then it'll all resolve itself?!

If not, I have no problem destroying everything just to start over. 👍

Either way, I will report back here and let you know of success or failure. Enjoy the weekend amigo!

**Comment by timothymamo** [comment]
Hey Jaime,

Glad the snapshot is now working. That's one issue out of the way 😄.

With regards to the domain, the only reason I can think of for you not being able to add it to the Domains section within DigitalOcean is because it is already being used somewhere else (i.e. it has been entered in the Domains section of another DigitalOcean account).

The terraform code won't run if you don't have the domain entered as it will give you the same error as before, even if the nameservers are pointing to the DigitalOcean ones (as they are doing now).

If this is still the case come Monday, I'd suggest you contact support so that they can see if anyone else is using that domain, and if it is and it isn't you get it resolved as you own the domain (you've changed the nameserevers so I would assume this, but they might need proof).

In any eventuality please do keep me informed to make sure I can help as much as possible.

> If not, I have no problem destroying everything just to start over. 👍

Turn it OFF and ON again has always been the go to in the industry 🤣 (I've used this method many a times).

Have a great weekend!

**Comment by timothymamo** [comment]
Hey @jjaimealeman, did you mange to get this to work with the above fix? If so I'll close this issue.

**Comment by jjaimealeman** [comment]
Feel free to close 👍 

I still couldn't get it to work as shown, but that's okay. I've decided to try my hand with installing Directus (headless CMS).
